### PR TITLE
Add PHP 8.1 support

### PR DESCRIPTION
**Pull request by paxal**
Hi :wave:

I'm trying to update my project to PHP 8.1 but it's not compatible due to [php_user_filter signature changes in typed properties](https://github.com/php/php-src/commit/8c97fc88f33bb7ee2882e62990f1ae42f06c60e6).

Moreover, there is a [modification in PHP 8.1 regarding SJIS](https://github.com/php/php-src/pull/7213/files#diff-014ac0ebf00226bd48a2486b1db4b0475c44492dbef0fc328a44a006cdb464c7R49-R56) I don't know how to address, so I removed the relevant chars from the tests.

Mainly because of 1), this version is only PHP 8.1 compatible (not compatible with PHP 7 nor 8.0)

### CODE REVIEW

**Comment by ericnorris** [comment]
Hey @paxal, thanks for your interest! I'll try to take an in-depth look this weekend.

For what it's worth, I think that due to #1 it's preferable to instead contribute an `mbstring` equivalent of [`convert.iconv.*`](https://www.php.net/manual/en/filters.convert.php#filters.convert.iconv) to https://github.com/php/php-src, rather than using this library. I've never been motivated enough to pursue this, however.

**Comment by ericnorris** [comment]
Hello again @paxal - I've renamed the default branch to `main` and switched to GitHub Actions instead of Travis CI; do you mind rebasing your change and making the necessary update to the CI workflow?

**Comment by ericnorris** [comment]
Thanks! I've approved the GitHub actions run, looks like there's a `phpunit` version upgrade change you'll need to make, since I had to pin to an earlier version for the previous PHP 7 build.

**Comment by paxal** [comment]
@ericnorris updated ! But still I'l check about `convert.iconv.*` filters :)

**Comment by Karpec** [comment]
Hi @ericnorris,
can you release new version with this fix? That would be great!

**Comment by ericnorris** [comment]
@Karpec done! @paxal thanks again.

**Pull request merged**
