### PR TITLE
Fixed: failure when leaving malformed byte sequence in $buffer variable

### PR DESCRIPTION
**Pull request by mya-zaki**
If you returns "PSFS_FEED_ME" on condition that letter string is more than "8192bytes",
$closing is false and $buffer is not empty, the data will be unavailable.

### CODE REVIEW

**Comment by ericnorris** [comment]
Hey @mya-zaki, thanks for contributing! I notice that CI is failing for your patch - could you address that?

**Comment by mya-zaki** [comment]
Thank you for your comment.
I'm sorry for the mistake. I modified it.

**Comment by ericnorris** [comment]
Thanks for the update. I took a look tonight but I'd like to poke around a bit more to see if I can understand exactly why this is failing. I'll plan to merge this by the end of the weekend regardless.

**Comment by ericnorris** [comment]
Hey again! I was able to reproduce with a minimal test case - if any data had been written to the bucket brigade and data was left in the buffer, returning `PSFS_FEED_ME` caused PHP to think there was no data in the buckets and ignored them.

I decided to patch the issue not by never returning `PSFS_FEED_ME`, but instead only returning it if no data had been written out.

Can you let me know if that fixes the issue on your end?

**Comment by mya-zaki** [comment]
Your fix is good.
My problem has been solved with it.

Thank you.

**Pull request closed without merging**
